background_opacity 0.8
dynamic_background_opacity yes
shell zsh
# Background / foreground
foreground              #e6c8cc
background              #0d0709

# Cursor
cursor                  #ff3347
cursor_text_color       #0d0709

# Selection
selection_foreground    #e6c8cc
selection_background    #4a151d

# URL
url_color               #ff6675

# Borders
active_border_color     #ff3347
inactive_border_color   #40151b
bell_border_color       #c92f40

# Tab bar
active_tab_foreground   #e6c8cc
active_tab_background   #6e1f2b
inactive_tab_foreground #80565d
inactive_tab_background #160a0d

# ═══════════════════════════════════════
#              ANSI COLORS
# ═══════════════════════════════════════

# Black
color0  #0d0709
color8  #4a252b

# Red
color1  #c92f40
color9  #ff3347

# Green
color2  #78966f
color10 #9fba8b

# Yellow
color3  #b9824e
color11 #d99a5e

# Blue
color4  #6f5860
color12 #a87880

# Magenta
color5  #92576a
color13 #c98296

# Cyan
color6  #806b70
color14 #b99da2

# White
color7  #c9b0b4
color15 #e6c8cc
