background_opacity 0.8
shell zsh

# Blood Moon
background #090204
foreground #e6b7b7

# Cursor
cursor #ff3b3b
cursor_text_color #090204

# Black
color0 #120507
color8 #3a0b12

# Red
color1 #b3132b
color9 #ff2947

# Green
color2 #58734a
color10 #8fa66a

# Yellow
color3 #a66a32
color11 #d69a4a

# Blue
color4 #4c526f
color12 #777da8

# Magenta
color5 #762d4a
color13 #b84d73

# Cyan
color6 #466b6b
color14 #6fa5a5

# White
color7 #b89b9b
color15 #f2dada
